import React,{useEffect,useRef,useState} from 'react';
import Sequence from './Sequence.jsx';
import {playBeat,prepareAudio,setSoundEnabled,startFinaleMusic,stopFinaleMusic,finishFinaleMusic} from './sound.js';
import {api} from '../api.js';
const labels=['Deletion key','Shutdown code','Control token','Escape route'];
const samples=['DEMO-DELETE','DEMO-SHUTDOWN','DEMO-CONTROL','DEMO-ROUTE'];
const artifactFields=['deletion_key','shutdown_code','control_token','route_code'];
export default function App({Vault,onVerifyArtifacts,onCompleteSequence,onHint}){
 const [values,setValues]=useState(['','','','']),[valid,setValid]=useState([]),[message,setMessage]=useState('Awaiting credentials from your crew.');
 const [gatewayBusy,setGatewayBusy]=useState(false),[serverSeconds,setServerSeconds]=useState(240),[serverResult,setServerResult]=useState(null);
 const teamId=Boolean(onVerifyArtifacts);
 const completionSent=useRef(false);
 const [stage,setStage]=useState('credentials'),[attempts,setAttempts]=useState(0),[hints,setHints]=useState(0),[deadline,setDeadline]=useState(null),[now,setNow]=useState(Date.now()),[frozen,setFrozen]=useState(null);
 const [beat,setBeat]=useState('vault'),[playback,setPlayback]=useState(0),[previewOnly,setPreviewOnly]=useState(false),[skip,setSkip]=useState(false),[showResults,setShowResults]=useState(true),[soundOn,setSoundOn]=useState(true),[crewSize,setCrewSize]=useState(4);
 const beats={vault:['Vault override accepted','The locks are withdrawing.'],tunnel:['Extraction route open','Follow the floor lights through the tunnel.'],boarding:['Transport in position','The loading bay is clear. Get the crew aboard.'],escape:['The crew is away','The transport is clear of the Mint.'],clear:['Extraction complete','The full crew made it out.']};
 useEffect(()=>{if(teamId)setMessage('Enter the four team artifacts and verify them with command.');},[teamId]);
 function watchFinale(){prepareAudio();startFinaleMusic();setPreviewOnly(true);setFrozen(300);setSkip(false);setShowResults(true);setBeat('vault');setPlayback(v=>v+1);setStage('opening')}
 function handleBeat(next){setBeat(next);playBeat(next)}
 function toggleSound(){const next=!soundOn;setSoundOn(next);setSoundEnabled(next)}
 const opening=stage==='opening'||stage==='complete';
 const remaining=frozen??(deadline?Math.max(0,Math.ceil((deadline-now)/1000)):300);
 const timer=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');
 useEffect(()=>{if(!deadline||opening||stage==='expired')return;const tick=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(tick)},[deadline,opening,stage]);
 useEffect(()=>{if(deadline&&remaining===0&&!opening)setStage('expired')},[remaining,deadline,opening]);

 async function verify(i){if(teamId){if(gatewayBusy)return;if(values.some((value,index)=>!value.trim()&&![2,3].includes(index))){setMessage('Enter the team-entered artifacts before using Verify.');return}setGatewayBusy(true);try{const result=await onVerifyArtifacts(Object.fromEntries(artifactFields.map((field,index)=>[field,values[index].trim()])));const next=artifactFields.map(field=>result.fields[field]?.valid===true);setValid(next.map((ok,index)=>ok?index:null).filter(index=>index!==null));if(result.time_remaining_seconds!==null)setServerSeconds(result.time_remaining_seconds);setMessage(result.message)}catch(error){setMessage(error.message)}finally{setGatewayBusy(false)}return}if(values[i].trim().toUpperCase()===samples[i]){setValid(v=>[...new Set([...v,i])]);setMessage(labels[i]+' accepted. Lock released.')}else setMessage('Credential not recognised. Check the sample credentials for this demo.')}
 function start(){setNow(Date.now());setDeadline(Date.now()+(teamId?serverSeconds:300)*1000);setStage('sequence')}
 async function complete(sequence){if(completionSent.current)return;const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(!teamId&&left===0){setStage('expired');return}if(onCompleteSequence){try{const result=await onCompleteSequence(sequence);if(!result.success){setAttempts(v=>v+1);setMessage(result.message);return false}setServerResult(result)}catch(error){setMessage(error.message);return false}}completionSent.current=true;prepareAudio();startFinaleMusic();setPreviewOnly(false);setSkip(false);setShowResults(true);setBeat('vault');setFrozen(left);setPlayback(v=>v+1);setStage('opening');return true}
 async function rejectSequence(sequence){setAttempts(v=>v+1);if(onCompleteSequence){try{const result=await onCompleteSequence(sequence);setMessage(result.message)}catch(error){setMessage(error.message)}}else{setDeadline(v=>v-30000);setNow(Date.now())}}
 function finishFinale(){finishFinaleMusic();setStage('complete')}
 function skipFinale(){stopFinaleMusic();setSkip(true)}
 function restart(){stopFinaleMusic();completionSent.current=false;setPreviewOnly(false);setSkip(false);setBeat('vault');setValues(['','','','']);setValid([]);setStage('credentials');setAttempts(0);setHints(0);setDeadline(null);setFrozen(null);setMessage('Awaiting credentials from your crew.')}
 useEffect(()=>()=>stopFinaleMusic(),[]);
 useEffect(()=>{if(stage==='opening')document.querySelector('.scene')?.scrollIntoView({behavior:'instant',block:'start'})},[stage,playback]);
 const score=serverResult?.final_score??Math.max(0,1000+remaining*5-12*20-attempts*150-hints*100);
 return <main><header><div className="brand"><span className="brand-icon">V</span> THE LAST EXIT <span className="edition">/ THE ESCAPE</span></div><span className="preview">PLAYABLE DEMO · 04</span></header><section className="topline"><span>PHASE 02 <b>/</b> MISSION 05</span><span>ROYAL MINT · EXTRACTION CHAMBER</span><span className="live">{stage==='credentials'?'SECURE CHANNEL':`EXTRACTION WINDOW / ${timer}`}</span></section>
 <div className={'layout '+(opening?'cinematic-layout ':'')+(stage==='opening'?'opening-layout ':'')+(stage==='sequence'?'sequence-layout':'')}><section className="scene"><div className="scene-title"><p className="eyebrow">{opening?'THE WAY OUT.':'ONE LAST DOOR.'}</p><h1>{stage==='complete'?'Crew':'Final'}<br/><em>{stage==='complete'?'extracted.':'extraction.'}</em></h1><p>{opening?'Follow the lights. Bring everyone home.':<>The plan got you in.<br/>The sequence gets you out.</>}</p></div><Vault crewSize={crewSize} unlocked={opening?4:valid.length} opening={opening} playback={playback} skip={skip} onBeat={handleBeat} onFinish={finishFinale}/><button className={'sound-toggle '+(opening?'sound-toggle-cinematic':'')} onClick={toggleSound} aria-pressed={soundOn}>{soundOn?'Mute sound':'Turn sound on'}</button>{stage==='opening'&&<><div className="cinematic-topline"><span>EXTRACTION FEED / {previewOnly?'PREVIEW':'LIVE'}</span><span>0{Math.min(Object.keys(beats).indexOf(beat)+1,4)} / 04</span></div><div key={beat} className={'cinematic-caption beat-'+beat} aria-live="polite"><span>{beat==='clear'?'EXTRACTION COMPLETE':'MISSION STATUS'}</span><strong>{beats[beat][0]}</strong><p>{beats[beat][1]}</p></div><button className="cinematic-skip" onClick={skipFinale}>Skip animation →</button></>}{stage==='complete'&&!showResults&&<button className="cinematic-score-toggle" onClick={()=>setShowResults(true)}>View extraction result ↑</button>}<div className="scene-bottom"><span>VAULT 05 / {opening?(beat==='vault'?'OPENING':'OPEN'):'SEALED'}</span><span>{opening?4:valid.length} / 4 LOCKS RELEASED</span></div></section>
 <aside>{stage==='credentials'?<><div className="step"><span>01</span><div><p className="eyebrow">EXTRACTION PROTOCOL</p><h2>Authenticate the heist</h2></div></div><p className="intro">Four operations. Four credentials.<br/>Bring the crew’s work together.</p><div className="credentials">{labels.map((label,i)=><form key={label} onSubmit={e=>{e.preventDefault();verify(i)}}><label htmlFor={'code'+i}><span>0{i+1} / {label}</span><span className={valid.includes(i)?'accepted':''}>{valid.includes(i)?'VERIFIED':'REQUIRED'}</span></label><div className="input-row"><input id={'code'+i} value={values[i]} disabled={valid.includes(i)||gatewayBusy||(teamId&&[2,3].includes(i))} placeholder={teamId&&[2,3].includes(i)?'Verified from team record':'Enter '+label.toLowerCase()} onChange={e=>setValues(v=>v.map((x,j)=>j===i?e.target.value:x))}/><button disabled={valid.includes(i)||gatewayBusy} type="submit">{valid.includes(i)?'✓':'Verify'}</button></div></form>)}</div><p className="feedback" role="status">{message}</p><button className="primary" disabled={valid.length<4} onClick={start}>Begin extraction sequence</button><details><summary>Try with sample credentials</summary><p>{teamId?'Event mode checks this team against the gateway. Sample credentials are for the standalone demo.':'Demo only. A five-minute timer starts when you begin the sequence. Event verification is not connected.'}</p><button className="sample" onClick={()=>{if(teamId){setMessage('Sample credentials are only for the standalone demo.');return}setValues(samples);setMessage('Sample credentials loaded. Verify each credential to release the locks.')}}>Fill sample credentials</button></details><div className="crew-setting"><label htmlFor="crew-size">Crew on transport</label><select id="crew-size" value={crewSize} onChange={e=>setCrewSize(Number(e.target.value))}><option value={3}>3 teammates</option><option value={4}>4 teammates</option></select></div><button className="sample preview-finale" onClick={watchFinale}>Preview finale · animation only</button></>:null}
 {stage==='sequence'&&<Sequence timer={timer} onComplete={complete} onPenalty={rejectSequence} onHint={()=>{setHints(v=>v+1);void onHint?.()}} isEventMode={teamId} attempts={attempts} hints={hints}/>}
 {stage==='complete'&&previewOnly&&showResults&&<div className="results"><button className="result-close" onClick={()=>setShowResults(false)} aria-label="View escape scene">×</button><p className="eyebrow">FINALE PREVIEW COMPLETE</p><h2>The crew is clear.</h2><p className="intro">Vault breached. Tunnel crossed. Transport clear of the Mint.</p><button className="primary" onClick={watchFinale}>Replay the animation</button><button className="sample preview-finale" onClick={restart}>Return to the mission</button><p className="demo-note">Animation preview only. No mission completion or score was recorded.</p></div>}
 {stage==='complete'&&!previewOnly&&showResults&&<div className="results"><button className="result-close" onClick={()=>setShowResults(false)} aria-label="View escape scene">×</button><p className="eyebrow">03 / HEIST COMPLETE</p><h2>No one left behind.</h2><p className="intro">The full crew is out. The plan is complete.</p><p className="score-label">{teamId?'AUTHORITATIVE HEIST SCORE':'DEMO EXTRACTION SCORE'}</p><strong className="score">{score.toLocaleString()}</strong><dl><div><dt>{teamId?'Money retained':'Money retained · sample'}</dt><dd>{teamId?`${serverResult?.breakdown.remaining_money?.toLocaleString()} credits`:'100,000 credits'}</dd></div><div><dt>Time remaining</dt><dd>{teamId?`${serverResult?.breakdown.remaining_seconds}s`:timer}</dd></div><div><dt>{teamId?'Accumulated risk':'Route risk · sample'}</dt><dd>{teamId?serverResult?.breakdown.accumulated_risk:'12'}</dd></div><div><dt>Wrong sequences</dt><dd>{attempts}</dd></div><div><dt>Hints used</dt><dd>{hints}</dd></div></dl>{!teamId&&<details><summary>How this demo score works</summary><p>Money ÷ 100 + seconds remaining × 5 − risk × 20 − wrong sequences × 150 − hints × 100. Minimum score: 0. Money and risk are sample values; event scoring weights are not final.</p></details>}<button className="primary" onClick={restart}>Replay the mission</button></div>}
 {stage==='expired'&&<div className="results"><p className="eyebrow">EXTRACTION WINDOW CLOSED</p><h2>The route is compromised.</h2><p className="intro">The countdown reached zero. Restart this demo to try a different sequence.</p><button className="primary" onClick={restart}>Retry the mission</button></div>}
 </aside></div><footer><span>“No one gets left behind.”</span><span>AUTHENTICATE <b>—</b> SEQUENCE <b>—</b> EXTRACT</span><span>DEMO / SAMPLE CREDENTIALS & SCORING</span></footer></main>
}
