import React,{useEffect,useRef,useState} from 'react';
import Sequence from './Sequence.jsx';
import {playBeat,prepareAudio,setSoundEnabled,startFinaleMusic,stopFinaleMusic,finishFinaleMusic} from './sound.js';
const labels=['Deletion key','Shutdown code','Control token','Escape route'];
const samples=['ERASE-7429','SILENT-031','MINT-OMEGA','NORTH-07'];
const artifactFields=['deletion_key','shutdown_code','control_token','route_code'];
const requiredOutputGames=['p2g1','p2g3','p2g4'];
export default function App({Vault}){
 const [values,setValues]=useState(['','','','']),[valid,setValid]=useState([]),[message,setMessage]=useState('Awaiting credentials from your crew.');
 const [gatewayConfigured,setGatewayConfigured]=useState(false),[teamState,setTeamState]=useState(null),[gatewayBusy,setGatewayBusy]=useState(false),[gatewayEligible,setGatewayEligible]=useState(false);
 const teamId=typeof window==='undefined'?'':(new URLSearchParams(window.location.search).get('team_id')||window.__CODEVERSE_TEAM_ID__||'').trim().toUpperCase();
 const completionSent=useRef(false);
 const [stage,setStage]=useState('credentials'),[attempts,setAttempts]=useState(0),[hints,setHints]=useState(0),[deadline,setDeadline]=useState(null),[now,setNow]=useState(Date.now()),[frozen,setFrozen]=useState(null);
 const [beat,setBeat]=useState('vault'),[playback,setPlayback]=useState(0),[previewOnly,setPreviewOnly]=useState(false),[skip,setSkip]=useState(false),[showResults,setShowResults]=useState(true),[soundOn,setSoundOn]=useState(true),[crewSize,setCrewSize]=useState(4);
 const beats={vault:['Vault override accepted','The locks are withdrawing.'],tunnel:['Extraction route open','Follow the floor lights through the tunnel.'],boarding:['Transport in position','The loading bay is clear. Get the crew aboard.'],escape:['The crew is away','The transport is clear of the Mint.'],clear:['Extraction complete','The full crew made it out.']};
 useEffect(()=>{let cancelled=false;async function connect(){try{const health=await fetch('/api/health').then(r=>r.json());if(cancelled)return;setGatewayConfigured(Boolean(health.gateway_configured));if(!teamId)return;if(!health.gateway_configured){setMessage('Gateway is not configured for this team. Demo mode is available without a team_id.');return}const response=await fetch('/api/teams/'+encodeURIComponent(teamId)+'/state');const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load team state.');if(cancelled)return;setTeamState(data);const outputs=data.outputs||{};const outputIds=health.shutdown_code_game_id?[...requiredOutputGames,health.shutdown_code_game_id]:requiredOutputGames;const missing=outputIds.some(id=>outputs[id]!=='present'&&outputs[id]!==true&&!outputs[id]?.present);const eligible=data.status==='active'&&data.unlocked?.includes('p2g5')&&!missing;setGatewayEligible(eligible);if(data.status!=='active')setMessage('This team is not active.');else if(!data.unlocked?.includes('p2g5'))setMessage('Final Extraction is not unlocked for this team yet.');else if(missing)setMessage('Required outputs from earlier games are not recorded for this team yet.');else setMessage('Team state loaded. Enter the four outputs and verify them with the gateway.');}catch(error){if(!cancelled&&teamId)setMessage('Gateway connection failed: '+error.message)} }void connect();return()=>{cancelled=true}},[teamId]);
 function watchFinale(){prepareAudio();startFinaleMusic();setPreviewOnly(true);setFrozen(300);setSkip(false);setShowResults(true);setBeat('vault');setPlayback(v=>v+1);setStage('opening')}
 function handleBeat(next){setBeat(next);playBeat(next)}
 function toggleSound(){const next=!soundOn;setSoundOn(next);setSoundEnabled(next)}
 const opening=stage==='opening'||stage==='complete';
 const remaining=frozen??(deadline?Math.max(0,Math.ceil((deadline-now)/1000)):300);
 const timer=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');
 useEffect(()=>{if(!deadline||opening||stage==='expired')return;const tick=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(tick)},[deadline,opening,stage]);
 useEffect(()=>{if(deadline&&remaining===0&&!opening)setStage('expired')},[remaining,deadline,opening]);

 async function verify(i){if(teamId){if(gatewayBusy)return;if(!gatewayConfigured||!gatewayEligible){setMessage('This team is not cleared for Final Extraction.');return}if(values.some(value=>!value.trim())){setMessage('Enter all four outputs before using Verify.');return}setGatewayBusy(true);try{const response=await fetch('/api/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({team_id:teamId,...Object.fromEntries(artifactFields.map((field,index)=>[field,values[index].trim()]))})});const result=await response.json();if(!response.ok)throw new Error(response.status===504?'Gateway response timed out; ask an organizer before resubmitting to avoid a duplicate attempt.':result.error||'Gateway verification failed.');const next=artifactFields.map(field=>result[field]===true);setValid(next.map((ok,index)=>ok?index:null).filter(index=>index!==null));setMessage(next.every(Boolean)?'All four outputs accepted. Lock released.':'Some outputs were not accepted. Correct the fields marked invalid and submit all four again.')}catch(error){setMessage(error.message)}finally{setGatewayBusy(false)}return}if(values[i].trim().toUpperCase()===samples[i]){setValid(v=>[...new Set([...v,i])]);setMessage(labels[i]+' accepted. Lock released.')}else setMessage('Credential not recognised. Check the sample credentials for this demo.')}
 async function sendGatewayEvent(type,meta={}){if(!teamId||!gatewayConfigured)return;try{const response=await fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({team_id:teamId,type,meta})});if(!response.ok)setMessage('The event could not be queued by the local adapter.')}catch{/* The adapter owns the durable retry queue once it receives the event. */}}
 function start(){setNow(Date.now());setDeadline(Date.now()+300000);setStage('sequence')}
 function complete(){if(completionSent.current)return;const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(left===0){setStage('expired');return}completionSent.current=true;void sendGatewayEvent('solved',{time_remaining_seconds:left});prepareAudio();startFinaleMusic();setPreviewOnly(false);setSkip(false);setShowResults(true);setBeat('vault');setFrozen(left);setPlayback(v=>v+1);setStage('opening')}
 function finishFinale(){finishFinaleMusic();setStage('complete')}
 function skipFinale(){stopFinaleMusic();setSkip(true)}
 function restart(){stopFinaleMusic();completionSent.current=false;setPreviewOnly(false);setSkip(false);setBeat('vault');setValues(['','','','']);setValid([]);setStage('credentials');setAttempts(0);setHints(0);setDeadline(null);setFrozen(null);setMessage('Awaiting credentials from your crew.')}
 useEffect(()=>()=>stopFinaleMusic(),[]);
 useEffect(()=>{if(stage==='opening')document.querySelector('.scene')?.scrollIntoView({behavior:'instant',block:'start'})},[stage,playback]);
 const score=Math.max(0,1000+remaining*5-12*20-attempts*150-hints*100);
 return <main><header><div className="brand"><span className="brand-icon">V</span> THE LAST EXIT <span className="edition">/ THE ESCAPE</span></div><span className="preview">PLAYABLE DEMO · 04</span></header><section className="topline"><span>PHASE 02 <b>/</b> MISSION 05</span><span>ROYAL MINT · EXTRACTION CHAMBER</span><span className="live">{stage==='credentials'?'SECURE CHANNEL':`EXTRACTION WINDOW / ${timer}`}</span></section>
 <div className={'layout '+(opening?'cinematic-layout ':'')+(stage==='opening'?'opening-layout ':'')+(stage==='sequence'?'sequence-layout':'')}><section className="scene"><div className="scene-title"><p className="eyebrow">{opening?'THE WAY OUT.':'ONE LAST DOOR.'}</p><h1>{stage==='complete'?'Crew':'Final'}<br/><em>{stage==='complete'?'extracted.':'extraction.'}</em></h1><p>{opening?'Follow the lights. Bring everyone home.':<>The plan got you in.<br/>The sequence gets you out.</>}</p></div><Vault crewSize={crewSize} unlocked={opening?4:valid.length} opening={opening} playback={playback} skip={skip} onBeat={handleBeat} onFinish={finishFinale}/><button className={'sound-toggle '+(opening?'sound-toggle-cinematic':'')} onClick={toggleSound} aria-pressed={soundOn}>{soundOn?'Mute sound':'Turn sound on'}</button>{stage==='opening'&&<><div className="cinematic-topline"><span>EXTRACTION FEED / {previewOnly?'PREVIEW':'LIVE'}</span><span>0{Math.min(Object.keys(beats).indexOf(beat)+1,4)} / 04</span></div><div key={beat} className={'cinematic-caption beat-'+beat} aria-live="polite"><span>{beat==='clear'?'EXTRACTION COMPLETE':'MISSION STATUS'}</span><strong>{beats[beat][0]}</strong><p>{beats[beat][1]}</p></div><button className="cinematic-skip" onClick={skipFinale}>Skip animation →</button></>}{stage==='complete'&&!showResults&&<button className="cinematic-score-toggle" onClick={()=>setShowResults(true)}>View extraction result ↑</button>}<div className="scene-bottom"><span>VAULT 05 / {opening?(beat==='vault'?'OPENING':'OPEN'):'SEALED'}</span><span>{opening?4:valid.length} / 4 LOCKS RELEASED</span></div></section>
 <aside>{stage==='credentials'?<><div className="step"><span>01</span><div><p className="eyebrow">EXTRACTION PROTOCOL</p><h2>Authenticate the heist</h2></div></div><p className="intro">Four operations. Four credentials.<br/>Bring the crew’s work together.</p><div className="credentials">{labels.map((label,i)=><form key={label} onSubmit={e=>{e.preventDefault();verify(i)}}><label htmlFor={'code'+i}><span>0{i+1} / {label}</span><span className={valid.includes(i)?'accepted':''}>{valid.includes(i)?'VERIFIED':'REQUIRED'}</span></label><div className="input-row"><input id={'code'+i} value={values[i]} disabled={valid.includes(i)||gatewayBusy} placeholder={'Enter '+label.toLowerCase()} onChange={e=>setValues(v=>v.map((x,j)=>j===i?e.target.value:x))}/><button disabled={valid.includes(i)||gatewayBusy} type="submit">{valid.includes(i)?'✓':'Verify'}</button></div></form>)}</div><p className="feedback" role="status">{message}</p><button className="primary" disabled={valid.length<4} onClick={start}>Begin extraction sequence</button><details><summary>Try with sample credentials</summary><p>{teamId?'Event mode checks this team against the gateway. Sample credentials are for the standalone demo.':'Demo only. A five-minute timer starts when you begin the sequence. Event verification is not connected.'}</p><button className="sample" onClick={()=>{if(teamId){setMessage('Sample credentials are only for the standalone demo.');return}setValues(samples);setMessage('Sample credentials loaded. Verify each credential to release the locks.')}}>Fill sample credentials</button></details><div className="crew-setting"><label htmlFor="crew-size">Crew on transport</label><select id="crew-size" value={crewSize} onChange={e=>setCrewSize(Number(e.target.value))}><option value={3}>3 teammates</option><option value={4}>4 teammates</option></select></div><button className="sample preview-finale" onClick={watchFinale}>Preview finale · animation only</button></>:null}
 {stage==='sequence'&&<Sequence timer={timer} onComplete={complete} onPenalty={()=>{setAttempts(v=>v+1);if(!teamId){setDeadline(v=>v-30000);setNow(Date.now())}void sendGatewayEvent('wrong_attempt',{source:'extraction_sequence'})}} onHint={()=>{setHints(v=>v+1);void sendGatewayEvent('hint_used',{source:'extraction_sequence'})}} attempts={attempts} hints={hints}/>}
 {stage==='complete'&&previewOnly&&showResults&&<div className="results"><button className="result-close" onClick={()=>setShowResults(false)} aria-label="View escape scene">×</button><p className="eyebrow">FINALE PREVIEW COMPLETE</p><h2>The crew is clear.</h2><p className="intro">Vault breached. Tunnel crossed. Transport clear of the Mint.</p><button className="primary" onClick={watchFinale}>Replay the animation</button><button className="sample preview-finale" onClick={restart}>Return to the mission</button><p className="demo-note">Animation preview only. No mission completion or score was recorded.</p></div>}
 {stage==='complete'&&!previewOnly&&showResults&&<div className="results"><button className="result-close" onClick={()=>setShowResults(false)} aria-label="View escape scene">×</button><p className="eyebrow">03 / HEIST COMPLETE</p><h2>No one left behind.</h2><p className="intro">The full crew is out. The plan is complete.</p><p className="score-label">DEMO EXTRACTION SCORE</p><strong className="score">{score.toLocaleString()}</strong><dl><div><dt>Money retained · sample</dt><dd>100,000 credits</dd></div><div><dt>Time remaining</dt><dd>{timer}</dd></div><div><dt>Route risk · sample</dt><dd>12</dd></div><div><dt>Wrong sequences</dt><dd>{attempts}</dd></div><div><dt>Hints used</dt><dd>{hints}</dd></div></dl><details><summary>How this demo score works</summary><p>Money ÷ 100 + seconds remaining × 5 − risk × 20 − wrong sequences × 150 − hints × 100. Minimum score: 0. Money and risk are sample values; event scoring weights are not final.</p></details><button className="primary" onClick={restart}>Replay the mission</button></div>}
 {stage==='expired'&&<div className="results"><p className="eyebrow">EXTRACTION WINDOW CLOSED</p><h2>The route is compromised.</h2><p className="intro">The countdown reached zero. Restart this demo to try a different sequence.</p><button className="primary" onClick={restart}>Retry the mission</button></div>}
 </aside></div><footer><span>“No one gets left behind.”</span><span>AUTHENTICATE <b>—</b> SEQUENCE <b>—</b> EXTRACT</span><span>DEMO / SAMPLE CREDENTIALS & SCORING</span></footer></main>
}
